### PR TITLE
Feat terminate sim

### LINKED ISSUE #213: Simulation method to request simulation termination
Looking to add a basic function to terminate a simulation through using a method that requests a simulation to end with the Simulation object.    Right now if you want to cleanly end a simulation early you need to exit the iterator within the simulation for loop like this:

```python
with Simulation("model") as sim:
    for ind, step in enumerate(sim):
        if ind == 9:
            break
```

So if we have a callback set for `before_step` that could have some basic functionality to end a simulation (like if you are deviating too far out some ideal depth or something). 

```python
with Simulation("model") as sim:
    nodeXYZ = Nodes(sim)["nodeZYX"]

    def before_step_callback():
        if nodeXYZ.depth > 8:
            sim.terminate_simulation()

    # Setting Callbacks
    sim.add_before_step(before_step_callback)

    for ind, step in enumerate(sim):
        # Now simulation will end early if the depth is > 8
        pass
```

Benefits - if you are running optimization it could save you computational time. 
Cons - if you like wasting money, you don't get to waste money anymore...

### PR DESCRIPTION
**Pull request by bemcdonnell**
Closes #213

### CODE REVIEW

**Comment by dickinsonre** [comment]
Is sloth an acronym?

**Comment by bemcdonnell** [comment]
@dickinsonre, haha we wish but it's not... @jennwuu loves sloths

**Comment by dickinsonre** [comment]
https://pbs.twimg.com/media/D8ey0ulWsAAGAkB?format=jpg&name=small

**Comment by dickinsonre** [comment]
Sloth update, we went to Costa Rica over the Xmas holidays and saw a few sloths.  They were using the power lines to cross the road and were actually traveling upside down pretty fast.

**Comment by jennwuu** [comment]
?!?!?! That's so awesome. Do you have any pictures? :O

**Comment by dickinsonre** [comment]
Yes, we have a lot of videos and pictures.  I will send you some of them.

**Pull request merged**
