### PR TITLE
[WIP] PR: Use linux/osx latest SWMM develop builds on CI testing

### PR DESCRIPTION
**Pull request by goanpeca**
@bemcdonnell SWMM now builds a dev package for every PR that gets merged and those packages are available at https://anaconda.org/OWA/libswmm/files

This PR is now using those packages for linux and osx. 

Also what is the point of bundling outdated libraries that do not work for linux and mac ?

---

I really do not like the current dll loading implementation, it seems to make incorrect assumptions. Library names are not standard on linux and mac (a `lib` is usually prepended) also, on Mac dylib are not loaded automatically by python so the full path is needed (maybe .so also). On Mac we could use either `.so` or `.dylib`.

Assuming that the user needs to replace some dlls/so/dylib on the site packages folder of pyswmm is also weird and unfriendly.

It would be better to just ask for the full path to load a given library, wherever the user has it available. This is explicit and avoids shadowing of libraries, if for any reason the win32 folder was polluted.

Also I think that we should not have the `use` method, we should just have an optional `library_path` as part of the init of Simulation class (that would propagate the option to PySMM).

Comments @bemcdonnell ?

---

Something is not working for linux and python 2.7. Will check later.

### CODE REVIEW

**Comment by goanpeca** [comment]
@bemcdonnell just to clarify I want to use
```python
class PySWMM(object):
    def __init__(self, inpfile='', rptfile=None, binfile=None,
                 library=None):
        ...
```
Where library can be the name plus extension (`libswmm5.so`, `libswmm5.dylib`, `swmm5.dll`) if those files live in the same folder as the script, otherwise use the full path, (`/somepath/libswmm5.so`, `/somepath/libswmm5.dylib`, `C:\somepath\swmm5.dll`) 

This make the whole process explicit and there is no chance of DLL hell on windows, dylib and so are correctly loaded on OSX

**Comment by bemcdonnell** [comment]
@goanpeca,

Have you looked at this of PR discussion in a while? https://github.com/OpenWaterAnalytics/pyswmm/pull/74

So you are not a big fan of the following implementation?

```python
import pyswmm
pyswmm.lib.use("swmm-goanpeca")

from pyswmm import Simulation,...
```
I've adopted this standard globally and I've really grown to like it.  I feel like we can achieve the same thing by using the `lib.use` implementation.  Do you agree or disagree?

**Comment by bemcdonnell** [comment]
@goanpeca, To be clear, I'm not saying "leave it as is".  I know the lib selector module can be improved...

**Comment by goanpeca** [comment]
>Have you looked at this of PR discussion in a while? #74

Yes, my mind has not changed that much from what I commented there

>So you are not a big fan of the following implementation?
import pyswmm
pyswmm.lib.use("swmm-goanpeca")
from pyswmm import Simulation,...

Not at all

It should be just
```python
import pyswmm
pyswmm.Simulation(library="swmm-goanpeca.so")
```

or 

```python
import pyswmm
pyswmm.Simulation(library="/somepath/swmm-goanpeca.so")
```

I dont like the idea of guessing what the user wants to do. If he wants to use a given library the user should point to that library in a fully qualified manner. 


>I've adopted this standard globally and I've really grown to like it. I feel like we can achieve the same thing by using the lib.use implementation. Do you agree or disagree?

I understand, but I dont' see the point of doing that based on the examples I just showed.

**Comment by bemcdonnell** [comment]
@goanpeca, you raise several good points and I'm seeing the value of what you are saying.  You also pointed out the current implementation is "globally" picking which engine to use - which is limiting.  

@stoiver and @abhiramm7, do you have any opinion on the engine selection implementation?

**Comment by abhiramm7** [comment]
> Besides a user should be able to run two simulation models step by step pointing to two different engines and comparing results. Setting the library globally breaks this completely. A library selector needs to be attached to a simulation not to a global module constant.

I like the idea of having the freedom to run the simulation on multiple engines. I am inclined towards having the engine attached to a simulation module rather than global module, if that is doable. I believe that if we can offer the user more freedom with out over complicating the usage, we should do so.

**Comment by goanpeca** [comment]
@bemcdonnell so, do you any further thoughts on this? I can continue to work on this so Linux and Mac users can start testing themselves (if they have the time to build with conda-build which is pretty straightforward)

**Comment by bemcdonnell** [comment]
@goanpeca, by default, and for the time being, how will this look and act for the windows user?

**Comment by bemcdonnell** [comment]
@goanpeca, i think this PR would solve a lot of our problems with synchronization between SWMM and PySWMM :-D

Do you want me to try to continue it?

**Comment by goanpeca** [comment]
@bemcdonnell by all means!, sorry I am super busy for a few weeks now :-(

**Pull request closed without merging**
