### PR TITLE
PR: Include the output toolkit api

### LINKED ISSUE #40: incorporate SWMMOutputAPI (Binary Reader)

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #40

### CODE REVIEW

**Comment by bemcdonnell** [comment]
@goanpeca Is this fully backwards compatible with py2.7?

**Comment by goanpeca** [comment]
Yes, we just need an extra dependency (enum34)

**Comment by bemcdonnell** [comment]
#40 Raised Issue Here

**Comment by bemcdonnell** [comment]
@goanpeca what is the common practice here for including source code (the actual C code)?

**Comment by bemcdonnell** [comment]
I only ask since the python wrapper is leverage some community based tools

**Comment by goanpeca** [comment]
>what is the common practice here for including source code (the actual C code)?

Well we normally bundle it in a src folder

**Comment by goanpeca** [comment]
should we merge?

**Comment by bemcdonnell** [comment]
Sure!

**Pull request merged**
