### PR TITLE
Make _error_check throw exception for all errcodes

### PR DESCRIPTION
**Pull request by dmcdougall**
Instead of swallowing the exception and turning into a warning.  Fixes
issue #172.

### CODE REVIEW

**Comment by bemcdonnell** [comment]
@dmcdougall, Thanks for the contribution! Looks like a couple tests need to be updated as well

**Comment by dmcdougall** [comment]
Cool, will get to those shortly.  Thanks for the feedback.

**Comment by bemcdonnell** [comment]
@dmcdougall, Do you plan to update the tests? If not, no problem - I can see if someone else can support you

**Comment by michaeltryby** [comment]
There is new api that fixes this problem in the swmm-python package.

**Comment by michaeltryby** [comment]
pyswmm could be the first package to build off the swmm-python foundation.

**Comment by dmcdougall** [comment]
I’m happy to update the tests.

Sorry for the slow response.  I can do this tomorrow.

Michael’s suggestion points to a different way to handle this situation.  Which direction do you folks prefer?  I can update the tests to swallow an expected exception (no simulation running) which seems reasonable for a test suite.  Or I can wait to build off of swmm-python.

**Comment by michaeltryby** [comment]
Sure effort is involved but I disagree with your characterization that it’s going to be a “large” one. There is one technical hurdle remaining, how to handle structs. Then it’s smooth sailing.

**Comment by dmcdougall** [comment]
What would you like me to do?  Fix up the PR or close it?

If I fix up the PR, the user will see graceful failures instead of seeing warning.  A consequence of this is that because of a current bug in swmm (https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/193) their application won’t exit with a useful message.

If I don’t fix up the PR, the user is left with a warning instead of an exception and could be misled into believing swmm is happy with an invalid internal state.

I can see arguments on both sides.

**Comment by bemcdonnell** [comment]
@dmcdougall, If you're keen to fix it (an update the tests), I'd say go for it! We will migrate the backend of this tool to use swmm-python ASAP.  We can release a patch fix after you make this change

**Comment by dmcdougall** [comment]
Ok, then I’ll update the tests.  Thanks for the guidance.

**Comment by dmcdougall** [comment]
Ah, right.  The error code is 309 which indicates a problem writing an output file.  I suppose the filesystem footprint on AppVeyor is limited and that's perhaps why.  I'll have a think about how to handle those.

**Comment by bemcdonnell** [comment]
@dmcdougall, i'm going to close and re-open to see if the Scrutinizer and Circle CI integrations go away... not sure what's going on with them...

**Pull request merged**
