### PR TITLE
LID Support

### LINKED ISSUE #192: latest version of v0.4.9.dev0 seems unstable
I tried a SWMM model run and it produced a very large high routing error. More info to follow.

### LINKED ISSUE #194: Add LID support to pyswmm
- Add programmatic access to LID objects in SWMM engine (before/during/after simulations)
- LID Objects include: LID control layer parameters, LID usage parameters, LID group (subcatchment) parameters
- Some LID parameter setters are enabled during model simulations such drain layer parameter and LID usage drain to parameter.

### LINKED ISSUE #196: Dropping python 2.7 support

### LINKED ISSUE #197: Adding support for python 64-bit

### PR DESCRIPTION
**Pull request by jennwuu**
Add LID support for API tools
Closes #192 
Closes #194 
Closes #196 
Closes #197

### CODE REVIEW

**Comment by limasierra** [comment]
Hi,
Removal of `pyswmm/lib/windows/swmm5.dll` seems to break the Windows version.
hth

**Comment by bemcdonnell** [comment]
@limasierra, the SWMM-API development for LID is side is still under construction.  https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/158
I suspect one this work is complete, the binaries will be updated here

**Comment by bemcdonnell** [comment]
@jennwuu, i don't think we have a linux build anymore. Can you add it to Travis Matrix?

**Comment by bemcdonnell** [comment]
@jennwuu, pointing this work to `develop` instead of `master`.  Looks like you might need to fix a merge conflict

**Comment by jennwuu** [comment]
@bemcdonnell can we update develop to match master?

**Pull request merged**
