### PR TITLE
Water quality updates

### PR DESCRIPTION
**Pull request by bemason**
1. Added pollutant getters for reactor_quality and inflow_quality for nodes and reactor_quality for links. 
2. Added pollutant setters for nodes and links. 
3. Tested these getters and setters. 

Cannot merge this pull request until swmm and swmm-python pull requests are completed.

### CODE REVIEW

**Comment by bemason** [comment]
Hi All! Just wanted to check in on next steps. Do we still have some things to finish up with swmm-python before we can add these changes to pyswmm? How can I help continue to move this along? :)

**Comment by bemason** [comment]
@jennwuu looks like swmm-python is not complete and we can move onto pyswmm. I believe my changes just need to be reviewed here?

**Comment by bemcdonnell** [comment]
@bemason, is it not or now complete? Assuming you meant “now.” So it looks like your branch is a tab but out of date. Would you like me to update it so we can run the unit tests?

**Comment by bemason** [comment]
@bemcdonnell yes, sorry I meant now*. And that would be great if you wouldn't mind. I'm still learning how to work on these shared projects on GitHub. Slow learning process!

**Comment by bemcdonnell** [comment]
@bemason no worries! Here to help! @jennwuu had to step away from the project for a couple months. @abhiramm7 and I can help from here.

**Comment by bemcdonnell** [comment]
@abhiramm7, can you push swmm-toolkit==0.9.0 to PYPI?

**Comment by abhiramm7** [comment]
Hey @bemason, can you update the PR to point to develop branch instead of master? The plan is to bring these additions into dev, prep for release, and then port them into master. Sorry it took this long. We are in the final stretch.

**Comment by bemason** [comment]
hey @abhiramm7  -- I believe I have updated the PR to point to develop instead of master. Let me know if I need to do something else. 

So exciting we are almost finished!! :D

**Comment by abhiramm7** [comment]
Awesome! Can you take a look at the tests? There seems to some merge issues as well. We want to fix them before merging our code in. Also, can update your PR to latest version of develop. 

Let me know if you have any questions. We can work through them.

**Comment by abhiramm7** [comment]
@bemason, I think you just need to bring the most recent develop branch into your PR. It should address most, if not all, the issues. Errors seem to be coming from dependencies in swmm-python 0.9.0. Let me know if you have any questions. 😁

**Review by abhiramm7 — APPROVED** [review]

**Pull request merged**
