### PR TITLE
add getters for pollutant surface buildup and ponded concentration in subcatchments

### PR DESCRIPTION
**Pull request by katmratliff**
- adds getters for `buildup` and `concPonded`
- removes `pollutant_buildup` from subcatchment statistics
- updates `tests_pollutants.py`

### CODE REVIEW

**Comment by bemcdonnell** [comment]
@katmratliff, I think it would be wise for us to track the git commit number in conjunction with the version of swmm we are packaging with pyswmm inside the `__init__.py` file:

https://github.com/OpenWaterAnalytics/pyswmm/blob/84368b0f05f67dec4e5b338c85e3e19ce8b9f5ab/pyswmm/__init__.py#L19

For example:
```python
__version__ = '.'.join(map(str, VERSION_INFO))
__swmm_version__ = '5.2.0.dev3'
__swmm_sha__ = "awer89q34rnoiaerer"
__author__ = 'Bryant E. McDonnell (EmNet LLC) - bemcdonnell@gmail.com'
```

**Comment by katmratliff** [comment]
@bemcdonnell great idea.

**Comment by Jiadalee** [comment]
@katmratliff  it seems there is a 'passing pointer to pointer into DLL'  problem from line 1139 to line 1142. Can you show me an example of the wrong values? I can help to test it in my side

**Comment by katmratliff** [comment]
Hi @Jiadalee, I assume you are talking about ll. 1139-1142 in swmm5.py? I'm not sure I understand what you mean by "can you show me an example of the wrong values?" This code has worked for me on windows and in linux, so more specific information about your problem would be helpful. Here is an example of how to access buildup and ponded concentration values:
https://github.com/katmratliff/pyswmm/blob/master/pyswmm/tests/test_pollutants.py

Note that you need to pass the specific pollutant name to return a numerical value.

**Comment by Jiadalee** [comment]
Hi @katmratliff , no. I mean in this link[file](https://github.com/OpenWaterAnalytics/pyswmm/pull/170/commits/107e2bfe70cecd0c39ccbbe7e3bacf270a58cc87). It says'not yet functional (returns values that aren't right)'

**Comment by katmratliff** [comment]
@Jiadalee you are looking at one commit when things were not fully functional yet - they should be now (or have been for me) with the most up-to-date version in my branch.

**Comment by Jiadalee** [comment]
@katmratliff Gotta! So this problem has been fixed and test_pollutant.py is based on the  this PR?

**Comment by katmratliff** [comment]
Yes @Jiadalee if you download and use the code from my [branch](https://github.com/katmratliff/pyswmm) you can use the functionality that is in the test_pollutant.py file (i.e., you can access pollutant loading and ponded concentration values during a simulation).

**Comment by Jiadalee** [comment]
@katmratliff Cool. Thanks. I starred your repo

**Comment by katmratliff** [comment]
@bemcdonnell remind me what needs to be tested/done here to pull this in?

**Comment by bemcdonnell** [comment]
@katmratliff, I think it's good. Maybe I forgot about it :(

**Comment by katmratliff** [comment]
Thanks @bemcdonnell! 🎉

**Pull request merged**
