### PR TITLE
Added CITATION.cff file to address #293

### LINKED ISSUE #293: Add Citation file
Add citation file using the CITATION.cff convention to direct users on how to cite pyswmm in publications.

### PR DESCRIPTION
**Pull request by cbuahin**
Added CITATION.cff file. 
Closes #293

### CODE REVIEW

**Review by jennwuu — COMMENTED** [review]
Is it possible to change Jennifer to Jia Xin (Jennifer) Wu?

**Comment by cbuahin** [comment]
> Is it possible to change Jennifer to Jia Xin (Jennifer) Wu?

Yes of course. Sorry about that. Do you have an ORCID by chance?

**Comment by jennwuu** [comment]
@cbuahin Nope, I do not. Thanks for putting this PR together!

**Comment by bemcdonnell** [comment]
@jennwuu is this PR ready to merge?

**Pull request merged**
