### PR TITLE
Updatetests

### PR DESCRIPTION
**Pull request by bemcdonnell**
Addresses Issue #105

### CODE REVIEW

**Comment by bemcdonnell** [comment]
@goanpeca, as i'm sure you can guess, Travis will not pass since we don't have updated binaries for Mac and Linux.

**Comment by bemcdonnell** [comment]
@stoiver and @abhiramm7,   @goanpeca is working on migrating our builds so we can keep the repo in sync.  You don't have to update anything right now, but realize that we are moving away from providing binaries here.

**Comment by stoiver** [comment]
@bemcdonnell, great idea to move away from providing binaries. I'll wait until @goanpeca  has finished before producing any new PR.

**Comment by bemcdonnell** [comment]
@stoiver, it sounds like we're going for a conda packaging structure. If you haven't already, you should check out Anaconda. I'm migrating most of my workflows to use that framework.

**Comment by stoiver** [comment]
@bemcdonnell, yes I have used conda (at least on windows). Indeed I just used it to get appveyor testing of anuga_core working. That was a bit tricky as I needed a gcc compiler for anuga_core and was able to install mingwpy from conda-forge to solve that problem.

**Pull request merged**
