### PR TITLE
PR: Update CI systems and badges on readme

### LINKED ISSUE #100: Update CI systems

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #100

### CODE REVIEW

**Comment by goanpeca** [comment]
@bemcdonnell OSX tests are failing :-p, don't have more time now to look into it. Will take a look tomorrow.

**Comment by bemcdonnell** [comment]
@abhiramm7, there might be an issue with a mac dependency for swmm. I was running into libgomp.1.dylib error on my mac. This might be a temporary issue until we get our packaging infrastructure setup using conda.

**Comment by bemcdonnell** [comment]
Also, @goanpeca, I believe we have Linux support coming in in the next week or two.

**Comment by abhiramm7** [comment]
Can you check the version of gcc you are using ? I used gcc-7, that addressed any issues with omp.

**Comment by goanpeca** [comment]
@abhiramm7 the errors are
```
E           OSError: dlopen(/Users/travis/build/OpenWaterAnalytics/pyswmm/pyswmm/lib/macos/swmm5.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
E             Referenced from: /Users/travis/build/OpenWaterAnalytics/pyswmm/pyswmm/lib/macos/swmm5.so
E             Reason: image not found

**Pull request closed without merging**
