### PR TITLE
Systemstats

### PR DESCRIPTION
**Pull request by bemcdonnell**
#91 Added some new functions and a new module

### CODE REVIEW

**Comment by bemcdonnell** [comment]
@michaeltryby, I guess the main question is is returning a tuple more or less "pythonic".  It seems to me that "pythonic" is touching these attributes via the `@property`.  

@goanpeca, what are your thoughts?

**Comment by goanpeca** [comment]
We can do any kind of wrpping on the python side so it can be 2 funcs on c code and 20 on python. We dont need to hace exact parity if it makes development harder on any side. Now I like how it looks on python. If on c two methods works better and is faster fine  b y me!

**Comment by bemcdonnell** [comment]
I think @michaeltryby's point is that instead of exposing a property for different items to call the same underlying function is that perhaps there might be another way... a way that is till Pythonic.  This only pertains to modules that are comprised of "getters" (and no setters).  

I am going to investigate descriptors with dictionaries and see if that might provide a more simple avenue to get at these.  I just opened up a few more API functions today which could easily lead to 60 more properties.  There has to be a better way than to write all these manually.   

@goanpeca, What are your thoughts?

**Comment by goanpeca** [comment]
>There has to be a better way than to write all these manually.

Whatever makes this non manual, or just adding a new func/constant to a list, would be great for the C side. In this case we only need to expose two things. Name of properties exposed (plus anything else needed, some text?) and the function that will go and fecth the info for us.

**Comment by dickinsonre** [comment]
I may be commenting out of turn but on the C side I got tired of keeping track of new variables so I made large arrays for the data - for example, this array for 200 Subcatchment  Saved variables
   // RED Advanced QA/QC 2017 ===========================
   double        SubResults[MAX_SUBCATCH_RESULTS];    // All Subcatchments Results // QA/QC RED 2017 
i then can use the results array with an index defined in enums.h 
here is an example
Subcatch[j].SubResults[SUBCATCH_IMPtoLID] =  qImperv;    // RED QA/QC 2017

**Comment by bemcdonnell** [comment]
This will get very interesting as the API gets bigger. 

@goanpeca The C Side is already pretty simple

`toolkitapi.c`
https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/toolkitapi/src/toolkitAPI.c#L766-L810

**Comment by goanpeca** [comment]
The best way to see this is by using the library actually, so  suggest opening an issue to create an examples folder illustrating the usage in more realistic situations, and there it will become more obvious if what we do is not optimal

**Pull request merged**
